[package]
name = "antsy"
version = "0.1.0"
edition = "2021"

[dependencies]

[features]
default = ["std"]
nested_styles = ["std"]
std = []

# benchmarks

[dev-dependencies]
criterion = "0.5"

colored = "2.1"
owo-colors = "4.0"

[[bench]]
name = "display"
harness = false
